In [71]:
import os
import pandas as pd
import numpy as np

## Reading in stop and frisk files from 2015-2018
files can be found here: https://www1.nyc.gov/site/nypd/stats/reports-analysis/stopfrisk.page

In [72]:
url1 = 'https://www1.nyc.gov/assets/nypd/downloads/excel/analysis_and_planning/stop-question-frisk/sqf-2018.xlsx'
sf18 = pd.read_excel(url1)

url2 = 'https://www1.nyc.gov/assets/nypd/downloads/excel/analysis_and_planning/stop-question-frisk/sqf-2017.xlsx'
sf17 = pd.read_excel(url2)

url3 = 'https://www1.nyc.gov/assets/nypd/downloads/excel/analysis_and_planning/stop-question-frisk/sqf-2016.csv'
sf16 = pd.read_csv(url3)

url4 = 'https://www1.nyc.gov/assets/nypd/downloads/excel/analysis_and_planning/stop-question-frisk/sqf-2015.csv'
sf15 = pd.read_csv(url4)

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0,1,2,3,4,8,18,19,73,74,84,85,86,103,110,111) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

# 2018 ##
- We want number of stops per year by precinct and if it resulted in an arrest 
- make sure precinct is a number

In [73]:
sf18.head()

,STOP_FRISK_ID,STOP_FRISK_DATE,Stop Frisk Time,YEAR2,MONTH2,DAY2,STOP_WAS_INITIATED,RECORD_STATUS_CODE,ISSUING_OFFICER_RANK,ISSUING_OFFICER_COMMAND_CODE,...,STOP_LOCATION_SECTOR_CODE,STOP_LOCATION_APARTMENT,STOP_LOCATION_FULL_ADDRESS,STOP_LOCATION_PREMISES_NAME,STOP_LOCATION_STREET_NAME,STOP_LOCATION_X,STOP_LOCATION_Y,STOP_LOCATION_ZIP_CODE,STOP_LOCATION_PATROL_BORO_NAME,STOP_LOCATION_BORO_NAME
0,1,2018-01-01,19:04:00,2018,January,Monday,Based on C/W on Scene,APP,POM,1,...,G,(null),VARICK STREET && FRANKLIN STREET,(null),VARICK STREET,982327,201274,(null),PBMS,MANHATTAN
1,2,2018-01-01,23:00:00,2018,January,Monday,Based on Radio Run,APP,POM,34,...,C,(null),DYCKMAN STREET && POST AVENUE,(null),DYCKMAN STREET,1004892,253548,(null),PBMN,MANHATTAN
2,3,2018-01-01,23:55:00,2018,January,Monday,Based on Radio Run,APP,POM,808,...,B,4M,2245 RANDALL AVENUE,(null),RANDALL AVENUE,1026706,237776,(null),PBBX,BRONX
3,4,2018-01-01,03:23:00,2018,January,Monday,Based on Radio Run,APP,POM,63,...,B,(null),EAST 38 STREET && AVENUE L,(null),EAST 38 STREET,1001347,166195,(null),PBBS,BROOKLYN
4,5,2018-01-01,03:23:00,2018,January,Monday,Based on Radio Run,APP,POM,63,...,B,(null),EAST 38 STREET && AVENUE L,(null),EAST 38 STREET,1001347,166195,(null),PBBS,BROOKLYN

In [74]:
# reducing df to columns of interest
sf18_a = sf18[['STOP_LOCATION_PRECINCT', 'SUSPECT_ARRESTED_FLAG', 'STOP_FRISK_ID']]

In [75]:
# counts number of yes_arrets and no_arrests per precinct
sf18_b = pd.pivot_table(sf18_a, columns='SUSPECT_ARRESTED_FLAG', index='STOP_LOCATION_PRECINCT', 
                        values='STOP_FRISK_ID', aggfunc='count').reset_index()

In [76]:
# renaming columns
sf18F = sf18_b.rename(index=str, columns={"SUSPECT_ARRESTED_FLAG": "index", "STOP_LOCATION_PRECINCT": "precinct",
                                         "N":"no_arrest", "Y":"yes_arrest"})

In [77]:
sf18F.isnull().values.any()

False

In [78]:
# checking to make sure precinct is float/int
sf18F.precinct.dtype

dtype('int64')

In [79]:
# adding year back in
sf18F['year'] = 2018

## 2017 data ##

In [80]:
sf17_a = sf17[['STOP_LOCATION_PRECINCT', 'SUSPECT_ARRESTED_FLAG', 'STOP_FRISK_ID']]

In [81]:
#value = sf181[sf181['SUSPECT_ARREST_FLAG']]
sf17_b = pd.pivot_table(sf17_a, columns='SUSPECT_ARRESTED_FLAG', index='STOP_LOCATION_PRECINCT', 
                        values='STOP_FRISK_ID', aggfunc='count').reset_index()

In [82]:
sf17_c = sf17_b.rename(index=str, columns={"STOP_LOCATION_PRECINCT": "precinct",
                                         "N":"no_arrest", "Y":"yes_arrest"})

In [83]:
sf17_c.isnull().values.any()

True

In [84]:
sf17F = sf17_c.dropna(axis=0, how='any')

In [85]:
sf17F.isnull().values.any()

False

In [86]:
sf17F['precinct'].replace(' ', np.nan, inplace=True)

/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:5886: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [87]:
sf17Final = sf17F.dropna(axis=0, how='any')

In [88]:
sf17Final.precinct.dtype

dtype('float64')

In [89]:
sf17Final['year'] = 2017

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

## 2016

In [90]:
sf161 = sf16.reset_index()

In [91]:
sf16_a = sf161[['pct', 'arstmade', 'index']]

In [92]:
#value = sf181[sf181['SUSPECT_ARREST_FLAG']]
sf16_b = pd.pivot_table(sf16_a, columns='arstmade', index='pct', values='index',
                        aggfunc='count').reset_index()

In [93]:
sf16_c = sf16_b.drop(columns=' ', axis=1)

In [94]:
sf16F = sf16_c.rename(index=str, columns={"pct": "precinct",
                                         "N":"no_arrest", "Y":"yes_arrest"})

In [95]:
sf16Final = sf16F.ix[:78,:] # after line 78, the precincts repeat with different numbers, so i just drop them

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

In [96]:
sf16Final.dropna(axis=0, how='any')

arstmade precinct  no_arrest  yes_arrest
0               1       46.0         7.0
1               5       63.0        17.0
2               6       22.0         9.0
3               7       41.0        12.0
4               9       63.0        17.0
5              10       52.0        13.0
6              13       68.0        25.0
7              14       99.0        22.0
8              17       31.0         7.0
9              18       85.0        13.0
10             19       53.0        38.0
11             20       31.0         3.0
12             22       23.0         1.0
13             23      226.0        57.0
14             24       85.0        17.0
15             25      162.0        46.0
16             26       40.0        11.0
17             28       69.0        13.0
18             30       77.0        17.0
19             32      126.0        46.0
20             33       19.0         1.0
21             34       68.0        15.0
22             40      139.0       130.0
23             41       87.0        24.0
24             42       69.0        55.0
25             43      105.0        62.0
26             44       87.0        10.0
27             45       32.0        17.0
28             46       73.0        11.0
29             47       74.0        43.0
..            ...        ...         ...
47             76       48.0        26.0
48             77       58.0         6.0
49             78       46.0         7.0
50             79      122.0        18.0
51             81       68.0        11.0
52             83       51.0        20.0
53             84      132.0        24.0
54             88       29.0         5.0
55             90      138.0        35.0
56             94       41.0         4.0
57            100       34.0         8.0
58            101       46.0        10.0
59            102       77.0         6.0
60            103       48.0        11.0
61            104       11.0         2.0
62            105      120.0        36.0
63            106      698.0        92.0
64            107       23.0         3.0
65            108       26.0         5.0
66            109      107.0        23.0
67            110       35.0        34.0
68            111       46.0        11.0
69            112       37.0         7.0
70            113       60.0        10.0
71            114      215.0        36.0
72            115       49.0        31.0
73            120      135.0        20.0
74            121       62.0        10.0
75            122      108.0        22.0
76            123       21.0        22.0

[77 rows x 3 columns]

In [97]:
sf16Final['precinct'].replace(' ', np.nan, inplace=True)
sf16Final.dropna(axis=0, how='any')

/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:5886: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

arstmade  precinct  no_arrest  yes_arrest
0              1.0       46.0         7.0
1              5.0       63.0        17.0
2              6.0       22.0         9.0
3              7.0       41.0        12.0
4              9.0       63.0        17.0
5             10.0       52.0        13.0
6             13.0       68.0        25.0
7             14.0       99.0        22.0
8             17.0       31.0         7.0
9             18.0       85.0        13.0
10            19.0       53.0        38.0
11            20.0       31.0         3.0
12            22.0       23.0         1.0
13            23.0      226.0        57.0
14            24.0       85.0        17.0
15            25.0      162.0        46.0
16            26.0       40.0        11.0
17            28.0       69.0        13.0
18            30.0       77.0        17.0
19            32.0      126.0        46.0
20            33.0       19.0         1.0
21            34.0       68.0        15.0
22            40.0      139.0       130.0
23            41.0       87.0        24.0
24            42.0       69.0        55.0
25            43.0      105.0        62.0
26            44.0       87.0        10.0
27            45.0       32.0        17.0
28            46.0       73.0        11.0
29            47.0       74.0        43.0
..             ...        ...         ...
47            76.0       48.0        26.0
48            77.0       58.0         6.0
49            78.0       46.0         7.0
50            79.0      122.0        18.0
51            81.0       68.0        11.0
52            83.0       51.0        20.0
53            84.0      132.0        24.0
54            88.0       29.0         5.0
55            90.0      138.0        35.0
56            94.0       41.0         4.0
57           100.0       34.0         8.0
58           101.0       46.0        10.0
59           102.0       77.0         6.0
60           103.0       48.0        11.0
61           104.0       11.0         2.0
62           105.0      120.0        36.0
63           106.0      698.0        92.0
64           107.0       23.0         3.0
65           108.0       26.0         5.0
66           109.0      107.0        23.0
67           110.0       35.0        34.0
68           111.0       46.0        11.0
69           112.0       37.0         7.0
70           113.0       60.0        10.0
71           114.0      215.0        36.0
72           115.0       49.0        31.0
73           120.0      135.0        20.0
74           121.0       62.0        10.0
75           122.0      108.0        22.0
76           123.0       21.0        22.0

[77 rows x 3 columns]

In [98]:
pd.to_numeric(sf16Final.precinct)

0       1.0
1       5.0
2       6.0
3       7.0
4       9.0
5      10.0
6      13.0
7      14.0
8      17.0
9      18.0
10     19.0
11     20.0
12     22.0
13     23.0
14     24.0
15     25.0
16     26.0
17     28.0
18     30.0
19     32.0
20     33.0
21     34.0
22     40.0
23     41.0
24     42.0
25     43.0
26     44.0
27     45.0
28     46.0
29     47.0
      ...
48     77.0
49     78.0
50     79.0
51     81.0
52     83.0
53     84.0
54     88.0
55     90.0
56     94.0
57    100.0
58    101.0
59    102.0
60    103.0
61    104.0
62    105.0
63    106.0
64    107.0
65    108.0
66    109.0
67    110.0
68    111.0
69    112.0
70    113.0
71    114.0
72    115.0
73    120.0
74    121.0
75    122.0
76    123.0
77      NaN
Name: precinct, Length: 78, dtype: float64

In [99]:
sf16Final.precinct.dtype

dtype('float64')

In [100]:
sf16Final['year'] = 2016

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

## 2015

In [101]:
sf15_a = sf15[['pct', 'arstmade', 'recstat']]

In [102]:
sf15_b = pd.pivot_table(sf15_a, columns='arstmade', index='pct', values='recstat',
                        aggfunc='count').reset_index()

In [103]:
sf15F = sf15_b.rename(index=str, columns={"pct": "precinct",
                                         "N":"no_arrest", "Y":"yes_arrest"})

In [104]:
sf15F.isnull().values.any()

False

In [106]:
sf15F['year'] = 2015

## Merging Dataframes

In [107]:
frames = [sf15F, sf16Final, sf17Final, sf18F]
frisks = pd.concat(frames)

In [108]:
frisks.head()

   precinct  no_arrest  yes_arrest  year
0       1.0       41.0         4.0  2015
1       5.0      160.0        27.0  2015
2       6.0       24.0         3.0  2015
3       7.0      136.0        29.0  2015
4       9.0      167.0        94.0  2015

In [109]:
frisks3 = frisks.dropna(axis=0, how='any')

In [110]:
frisks3.isnull().values.any()

False

In [111]:
len(frisks3.precinct.unique())

77

In [112]:
#frisks3.to_csv('StopFrisk_15thru18.csv')